# @name login
POST https://odin-blog.fly.dev/users/login
Content-Type: application/json

{
  "email":"aaaa@b.com",
  "password":"12345"
}

###
# @forceref login
https://odin-blog.fly.dev/blog/user_articles_list/6672c934daef17ac02661e60
Content-Type: application/json
Authorization: Bearer {{login.token}}